import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style>{`.${inter.className} { ${inter.cssText} }`}</style>
        {/* Other head elements */}
      </head>
      <body>
        {children}
        <footer>
          <p>Pie de página</p>
        </footer>
      </body>
    </html>
  );
}
